
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const Admin = lazy(() => import("./pages/Admin.tsx"));
const AdminDashboard = lazy(() => import("./pages/AdminDashboard.tsx"));
const AdminLogin = lazy(() => import("./pages/AdminLogin.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const ApplicationSubmitted = lazy(() => import("./pages/ApplicationSubmitted.tsx"));
const CaregiverApplication = lazy(() => import("./pages/CaregiverApplication.tsx"));
const CaregiverProfile = lazy(() => import("./pages/CaregiverProfile.tsx"));
const ClientApplication = lazy(() => import("./pages/ClientApplication.tsx"));
const ClientForm = lazy(() => import("./pages/ClientForm.tsx"));
const ClientProfile = lazy(() => import("./pages/ClientProfile.tsx"));
const LocationMatching = lazy(() => import("./pages/LocationMatching.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/admin", element: <Admin />},
	{ path: "/admin-dashboard", element: <AdminDashboard />},
	{ path: "/admindashboard", element: <AdminDashboard />},
	{ path: "/admin-login", element: <AdminLogin />},
	{ path: "/adminlogin", element: <AdminLogin />},
	{ path: "/", element: <App />},
	{ path: "/application-submitted", element: <ApplicationSubmitted />},
	{ path: "/applicationsubmitted", element: <ApplicationSubmitted />},
	{ path: "/caregiver-application", element: <CaregiverApplication />},
	{ path: "/caregiverapplication", element: <CaregiverApplication />},
	{ path: "/caregiver-profile", element: <CaregiverProfile />},
	{ path: "/caregiverprofile", element: <CaregiverProfile />},
	{ path: "/client-application", element: <ClientApplication />},
	{ path: "/clientapplication", element: <ClientApplication />},
	{ path: "/client-form", element: <ClientForm />},
	{ path: "/clientform", element: <ClientForm />},
	{ path: "/client-profile", element: <ClientProfile />},
	{ path: "/clientprofile", element: <ClientProfile />},
	{ path: "/location-matching", element: <LocationMatching />},
	{ path: "/locationmatching", element: <LocationMatching />},
	{ path: "/login", element: <Login />},

];
